PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX udfrs:<http://udfr.org/onto#>
SELECT ?fileFormat ?fileFormatPuid
{
  ?fileFormat udfrs:aliasIdentifier ?fileFormatIdentifier.
  ?fileFormatIdentifier rdf:type udfrs:Identifier;
      udfrs:identifierNamespaceType udfrs:PUID;
      udfrs:identifierValue ?fileFormatPuid
      FILTER (?fileFormatPuid = "%s")
}