PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX udfrs:<http://udfr.org/onto#>
SELECT ?mimetype ?extension
{
  <%s> udfrs:mimeType ?mimetypeIdentifier;
      udfrs:signature ?signatureIdentifier.
  ?mimetypeIdentifier rdfs:label ?mimetype.
  ?signatureIdentifier udfrs:signatureType udfrs:FileExtension;
      udfrs:signatureValue ?extension.
}
LIMIT 1
