PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX service:<http://www.daml.org/services/owl-s/1.2/Service.owl#>
PREFIX profile:<http://www.daml.org/services/owl-s/1.2/Profile.owl#>
PREFIX process:<http://www.daml.org/services/owl-s/1.2/Process.owl#>
PREFIX dArceoProfile:<http://darceo.psnc.pl/ontologies/dArceoProfile.owl#>
PREFIX dArceoProcess:<http://darceo.psnc.pl/ontologies/dArceoProcess.owl#>
SELECT ?result ?condition ?format
WHERE {
  <%s> rdf:type service:Service;
      service:presents ?profile.
  ?profile profile:hasResult ?result.
  ?result process:inCondition ?rules.
  ?rules dArceoProcess:inputFileCondition ?condition.
  ?condition dArceoProcess:inputFileFormat ?format.
}
