PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX service:<http://www.daml.org/services/owl-s/1.2/Service.owl#>
PREFIX profile:<http://www.daml.org/services/owl-s/1.2/Profile.owl#>
PREFIX dArceoService:<http://darceo.psnc.pl/ontologies/dArceoService.owl#>
PREFIX dArceoProfile:<http://darceo.psnc.pl/ontologies/dArceoProfile.owl#>
SELECT DISTINCT ?service1 ?inpuid1 ?outpuid1 ?service2 ?inpuid2 ?outpuid2 ?service3 ?inpuid3 ?outpuid3
WHERE {
  {
  ?transformation rdf:type dArceoService:FileTransformation;
      dArceoService:fileIn <%s>;
	  dArceoService:fileOut <%s>;
	  dArceoService:performedBy ?service;
	  dArceoService:previousTransformation ?previous;
	  dArceoService:subsequentTransformation ?subsequent.
  ?previous dArceoService:previousTransformation ?previousprevious;
      dArceoService:subsequentTransformation ?previoussubsequent.
  ?previousprevious dArceoService:performedBy ?service1;
      dArceoService:fileIn ?inpuid1;
	  dArceoService:fileOut ?outpuid1.
  ?previoussubsequent dArceoService:performedBy ?service2;
      dArceoService:fileIn ?inpuid2;
	  dArceoService:fileOut ?outpuid2.
  ?subsequent dArceoService:performedBy ?service3;
      dArceoService:fileIn ?inpuid3;
	  dArceoService:fileOut ?outpuid3.
  FILTER (!isBlank(?previousprevious) && !isBlank(?previoussubsequent) && !isBlank(?subsequent) && <%s> = ?inpuid1 && ?outpuid1 = ?inpuid2 && ?outpuid2 = ?inpuid3 && ?outpuid3 = <%s>)
  }
  UNION
  {
  ?transformation rdf:type dArceoService:FileTransformation;
      dArceoService:fileIn <%s>;
	  dArceoService:fileOut <%s>;
	  dArceoService:performedBy ?service;
	  dArceoService:previousTransformation ?previous;
	  dArceoService:subsequentTransformation ?subsequent.
  ?subsequent dArceoService:previousTransformation ?subsequentprevious;
      dArceoService:subsequentTransformation ?subsequentsubsequent.
  ?previou dArceoService:performedBy ?service1;
      dArceoService:fileIn ?inpuid1;
	  dArceoService:fileOut ?outpuid1.
  ?subsequentprevious dArceoService:performedBy ?service2;
      dArceoService:fileIn ?inpuid2;
	  dArceoService:fileOut ?outpuid2.
  ?subsequentsubsequent dArceoService:performedBy ?service3;
      dArceoService:fileIn ?inpuid3;
	  dArceoService:fileOut ?outpuid3.
  FILTER (!isBlank(?previous) && !isBlank(?subsequentprevious) && !isBlank(?subsequentsubsequent) && <%s> = ?inpuid1 && ?outpuid1 = ?inpuid2 && ?outpuid2 = ?inpuid3 && ?outpuid3 = <%s>)
  }
}
